name: Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        password: ${{ secrets.HOSTINGER_PASSWORD }}
        port: 65002
        script: |
          cd /home/u664918047/domains/lightgrey-seahorse-783260.hostingersite.com/public_html
          rm -rf * .*
          git clone https://github.com/pixel12digital/agroneg.git temp_deploy
          cp -r temp_deploy/* .
          cp -r temp_deploy/.* . 2>/dev/null || true
          rm -rf temp_deploy
          chmod -R 755 .
          chmod -R 777 uploads/
